name: cityvoice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.3.0
  shared_preferences: ^2.0.18
  image_picker: ^0.8.5+3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.0.1
  path: ^1.8.0
  http_parser: ^4.0.2
  jwt_decoder: 2.0.1
  fl_chart: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
